In [88]:
# pip install faiss-cpu

In [89]:
import faiss
from sentence_transformers import SentenceTransformer
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [90]:
data=open('data.txt').read()

In [ ]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size=200,
    chunk_overlap=40
)
chunks = splitter.split_text(data)

In [92]:
embedding_model = SentenceTransformer(
    model_name_or_path= 'sentence-transformers/all-miniLM-L6-V2'
)

In [93]:
embeddings = embedding_model.encode(chunks).astype('float32')

In [94]:
embeddings

array([[-5.10745570e-02, -3.63585763e-02,  6.47429228e-02, ...,
        -2.59837322e-02,  6.67559728e-02, -2.12414004e-02],
       [-3.65922228e-02,  8.16841573e-02, -2.94340774e-02, ...,
         9.33288410e-03, -5.85482046e-02, -2.94650663e-02],
       [-7.38152340e-02, -2.04329602e-02,  2.66191810e-02, ...,
         2.30889786e-02, -3.38193066e-02,  2.13478841e-02],
       ...,
       [ 1.61914062e-02, -4.46705110e-02, -3.93849223e-05, ...,
         6.11671666e-03, -5.97641319e-02,  6.23781048e-02],
       [-8.50615203e-02, -8.78285542e-02,  2.74528563e-02, ...,
        -4.11655977e-02,  2.15746816e-02, -6.03978112e-02],
       [-1.18979126e-01, -4.25544418e-02, -5.63978739e-02, ...,
        -9.80486944e-02, -1.84083991e-02,  1.03334650e-01]],
      shape=(4000, 384), dtype=float32)

In [95]:
dimension = embeddings.shape[1]

In [96]:
faiss.normalize_L2(embeddings)

In [97]:
index = faiss.IndexFlatIP(dimension) #dot product
# index = faiss.IndexFlatIP() #euclidean distance

In [98]:
index.add(embeddings) #stored embeddings inside faiss DB

#### Search Method(R)

In [99]:
Query = 'Explain Machine Learning ?'

In [100]:
query_embeddings = embedding_model.encode(Query).astype('float32')

In [101]:
query_embeddings = query_embeddings.reshape(1,-1)
query_embeddings

array([[-1.24870995e-02, -2.93795262e-02,  3.04286014e-02,
         1.55044086e-02,  5.17589375e-02, -3.45747098e-02,
        -3.30067426e-03, -2.68255826e-02, -2.55472176e-02,
        -1.16211707e-02, -6.04346097e-02,  3.57628539e-02,
         4.54586893e-02, -8.03951994e-02, -8.29185992e-02,
        -7.45701184e-03, -3.19553949e-02,  2.52576377e-02,
        -9.97759998e-02, -1.09578513e-01,  5.82825392e-02,
        -3.63752581e-02, -6.94946274e-02,  2.50929780e-02,
         2.06710864e-02,  5.07701710e-02,  3.87980752e-02,
         6.04338795e-02,  1.48697384e-02, -9.96478461e-03,
         2.40478348e-02, -1.68944411e-02,  4.03817706e-02,
         3.85295935e-02, -8.52659345e-02,  2.62187850e-02,
        -4.54908684e-02,  4.75514829e-02,  1.19168814e-02,
         5.42534553e-02, -4.02193516e-02, -5.95136397e-02,
        -5.54296095e-03,  2.07223929e-02,  1.39104158e-01,
         8.75249058e-02, -3.82022783e-02, -6.54590353e-02,
        -1.47253852e-02, -5.12091480e-02, -1.56483650e-0

In [102]:
query_embeddings.shape

(1, 384)

In [103]:
faiss.normalize_L2(query_embeddings)

In [104]:
query_embeddings

array([[-1.24870995e-02, -2.93795262e-02,  3.04286014e-02,
         1.55044086e-02,  5.17589375e-02, -3.45747098e-02,
        -3.30067426e-03, -2.68255826e-02, -2.55472176e-02,
        -1.16211707e-02, -6.04346097e-02,  3.57628539e-02,
         4.54586893e-02, -8.03951994e-02, -8.29185992e-02,
        -7.45701184e-03, -3.19553949e-02,  2.52576377e-02,
        -9.97759998e-02, -1.09578513e-01,  5.82825392e-02,
        -3.63752581e-02, -6.94946274e-02,  2.50929780e-02,
         2.06710864e-02,  5.07701710e-02,  3.87980752e-02,
         6.04338795e-02,  1.48697384e-02, -9.96478461e-03,
         2.40478348e-02, -1.68944411e-02,  4.03817706e-02,
         3.85295935e-02, -8.52659345e-02,  2.62187850e-02,
        -4.54908684e-02,  4.75514829e-02,  1.19168814e-02,
         5.42534553e-02, -4.02193516e-02, -5.95136397e-02,
        -5.54296095e-03,  2.07223929e-02,  1.39104158e-01,
         8.75249058e-02, -3.82022783e-02, -6.54590353e-02,
        -1.47253852e-02, -5.12091480e-02, -1.56483650e-0

In [105]:
''' 
1st value - > distance
2nd value -> 
'''
index.search(query_embeddings,k=5)

(array([[0.5725651 , 0.55650294, 0.55401886, 0.54956055, 0.5445618 ]],
       dtype=float32),
 array([[3488, 2208,  768, 2848,  608]]))

In [106]:
index.search

<bound method handle_Index.<locals>.replacement_search of <faiss.swigfaiss_avx2.IndexFlatIP; proxy of <Swig Object of type 'faiss::IndexFlatIP *' at 0x000002084179B1E0> >>